apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: purubaranwal/onilne-exam-voting-redis:latest
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/redis-healthcheck.sh
          initialDelaySeconds: 5
          periodSeconds: 10

