apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: debug
      port: 9229
  selector:
    app: result-app
  type: LoadBalancer

