apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: external
      port: 5000
  selector:
    app: voting-app
  type: LoadBalancer

