apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: purubaranwal/onilne-exam-voting-worker:latest
        env:
          - name: REDIS
            value: "redis"
          - name: POSTGRES
            value: "postgres"

